theme: "archie"
baseURL: https://tomparkinson.netlify.app/
languageCode: en-us
title: "Tom Parkinson"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Basic Info
markup:
  goldmark:
    renderer:
      unsafe: true

# Social Icons
icon:
  pack:
    ai: true

# Page parameters
params:
  mode: toggle
  useCDN: false
  subtitle: ""
  hometext: | 
          Hello! I made this website to serve as single repository for my work. There is not much more context than that. <br /><br />
          My [research](/research) is focused on technologies and design solutions to improve wellbeing in the built environment. 
          I have a decade of experience in laboratory and field research that combines building physics, human perception, data science, 
          and sensor technologies. The nitty-gritty details are in [publications](/publications) I've authored. <br /><br />
          I also do data science [projects](/projects) on the side. I use `R` in my work to translate data into actionable insights.
  site_type: "Person"
  local_business_type: ""
  description: "A personal site by Tom Parkinson"
  
  # Social Tags
  social:
    - name: LinkedIn
      icon: linkedin
      url: 'https://www.linkedin.com/in/thomas-c-parkinson/'
    - name: "Google Scholar"
      icon: book-open
      url: 'https://github.com/tom-parkinson'
    - name: ORCID
      icon: book
      url: 'https://orcid.org/0000-0002-0088-8754'
    - name: GitHub
      icon: github
      url: 'https://github.com/tom-parkinson'
      
# Main menu Items
menu:
  main:
    - name: Research
      url: /research
      weight: 2
    - name: Publications
      url: /publications
      weight: 3
    - name: Projects
      url: /projects
      weight: 4
