theme: "archie"
baseURL: https://tomparkinson.netlify.app/
languageCode: en-us
title: "Tom Parkinson"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Basic Info
markup:
  goldmark:
    renderer:
      unsafe: true

# Social Icons
icon:
  pack:
    ai: true

# Page parameters
params:
  mode: toggle
  useCDN: false
  subtitle: ""
  hometext: "I made this site as a spot to put all my work. Not much context other than I do research and write R code. You'll find a bit of both here :-)"
  site_type: "Person"
  local_business_type: ""
  description: "A personal site by Tom Parkinson"
  
  # Social Tags
  social:
    - name: LinkedIn
      icon: linkedin
      url: 'https://www.linkedin.com/in/thomas-c-parkinson/'
    - name: GitHub
      icon: github
      url: 'https://github.com/tom-parkinson'
      
# Main menu Items
menu:
  main:
    - name: Research
      url: /research
      weight: 2
    - name: Publications
      url: /publications
      weight: 3
    - name: Projects
      url: /projects
      weight: 4
