---
title: "Research"
author: "Tom Parkinson"
date: '`r format(Sys.time(), "%B  %Y")`'
categories: ["Research"]
#tags: ["Research"]
---

```{r setup, include = FALSE}

# define knitr settings
knitr::opts_chunk$set(collapse = TRUE)



```

 <br />

I'm interested in high performance buildings that enhance occupant comfort and well-being. This includes indoor environmental quality, application of sensor technologies to built environments, psychophysics, and human thermal physiology & comfort.

Below is an overview of some of the research I've done over the last 10 years. Please reach out if you'd like more details.


# Occupant surveys

I'm currently responsible for the [CBE Occupant Survey](https://cbe.berkeley.edu/resources/occupant-survey/), one of the largest and longest-running post-occupancy evaluation tools. Along with managing the survey tool, I also analyse the database of 90,000 responses from over 800 office buildings. I've published work [summarising the survey](https://doi.org/10.5334/bc.76) and exploring the source of [occupant dissatisfaction](https://doi.org/10.1016/j.buildenv.2021.108270).

Much of the survey project involves working closely with industry partners to evaluate their office buildings. Some of these organisations include International WELL Building Institute, Salesforce, Atelier Ten, Gensler, and Arup.


# Wildfire resilience

I was recently awarded [seed-funding](https://citris-uc.org/13-cross-campus-projects-selected-for-2021-seed-awards/) to develop a technological intervention to help mitigate the health impacts of wildfire smoke in Californian homes. Fine particulate matter is the largest environmental risk factor for human health and death in California, and wildfires in the western United States are a major source. This project will develop software that programs smart thermostats to adjust ventilation system operation based on outdoor particulate concentrations to ensure adequate indoor air quality. The aim is to improve public health and climate resilience in residential buildings.


